# Generated by Django 3.2.4 on 2021-09-22 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo2', '0003_confirmstring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmstring',
            name='c_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
