# Generated by Django 3.2.4 on 2021-08-26 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id_location', models.IntegerField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=20)),
                ('city', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id_travel', models.IntegerField(primary_key=True, serialize=False)),
                ('target', models.CharField(max_length=100)),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
                ('companion', models.CharField(max_length=100)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='demo2.location')),
            ],
        ),
    ]
