version: '3'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    image: docker2
    container_name: d2
    hostname: django
    restart: always
    command: python manage.py runserver 0.0.0.0:8000 --insecure
    volumes:
      - .:/website
    ports:
      - "80:8000"
    depends_on:
      - mysql

  mysql:
    image: mysql
    container_name: mysql
    hostname: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password --mysqlx=0 #encryption
    ports:
      - 3308:3306 #3306 local used
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_HOST=localhost 
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=demo2
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=test123
      - MYSQL_ROOT_PASSWORD=test123